#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 17 12:14:04 2021

@author: lester
"""

from get_latest_historical_data import get_latest_historical_data
import pandas as pd

df = pd.DataFrame(get_latest_historical_data('ali'))
df.describe()

pct_change = df.close.pct_change()
